### ISSUE TITLE
Скрины логов

### ISSUE THREAD

**Issue by GurinaElena** [GurinaElena/dockerfirstlesson#1]
Добрый день, помогите, пожалуйста, разобраться с логами.

1. После команды docker-compose up. Сначала пишет что упала, потом что готова к соединению, не очень понятно,но я потом запустила jar-файл и результат на втором и третьем скриншотах. Попыталась перевести, но ошибку так и не поняла. Может yml-не правильно прописан?
[image](https://user-images.githubusercontent.com/59961907/91011900-d7dfce00-e5ed-11ea-92a7-26246452d5a1.png)

![image](https://user-images.githubusercontent.com/59961907/91012465-d367e500-e5ee-11ea-8289-621c112c1848.png)

![image](https://user-images.githubusercontent.com/59961907/91012037-0e1d4d80-e5ee-11ea-9753-c3d1baa0827b.png)

**Comment by ArRomanov** [comment]
Добрый день!
У вас в файле application.properties в адресе к БД нужно изменить порт на 5432, это стандартный порт для postgres.

И на всякий случай уточню про ОС. Если у вас win10 (не pro) или win7/8, то вместо localhost нужно писать ip, который вам показывает docker toolbox после запуска.
